import { Router, type IRouter } from "express";
import healthRouter from "./health";
import customersRouter from "./customers";
import bookingsRouter from "./bookings";
import dressesRouter from "./dresses";
import rentalsRouter from "./rentals";
import paymentsRouter from "./payments";
import dashboardRouter from "./dashboard";
import tasksRouter from "./tasks";
import quotesRouter from "./quotes";
import servicesRouter from "./services";
import accountingRouter from "./accounting";
import staffRouter from "./staff";
import settingsRouter from "./settings";
import expensesRouter from "./expenses";
import contractsRouter from "./contracts";
import payrollsRouter from "./payrolls";
import pricingRouter from "./pricing";
import salaryRatesRouter from "./salary-rates";
import staffRatesRouter from "./staff-rates";
import staffCastRouter from "./staff-cast";
import jobEarningsRouter from "./job-earnings";
import staffProfileRouter from "./staff-profile";
import photoshopJobsRouter from "./photoshop-jobs";
import internalCommsRouter from "./internal-comms";
import storageRouter from "./storage";

const router: IRouter = Router();

router.use(healthRouter);
router.use(customersRouter);
router.use(bookingsRouter);
router.use(dressesRouter);
router.use(rentalsRouter);
router.use(paymentsRouter);
router.use(dashboardRouter);
router.use(tasksRouter);
router.use(quotesRouter);
router.use(servicesRouter);
router.use(accountingRouter);
router.use(staffRouter);
router.use(settingsRouter);
router.use(expensesRouter);
router.use(contractsRouter);
router.use(payrollsRouter);
router.use(pricingRouter);
router.use(salaryRatesRouter);
router.use(staffRatesRouter);
router.use(staffCastRouter);
router.use(jobEarningsRouter);
router.use(staffProfileRouter);
router.use(photoshopJobsRouter);
router.use(internalCommsRouter);
router.use(storageRouter);

export default router;
